### ISSUE TITLE
Remove 404 

### ISSUE THREAD

**Issue by ivanmauricio** [fac25/week2-db-Sumithra-Joe-Paz-Abdullah#49]
You don't need a 404 error here. Simply telling the user that no locations were found is enough.

https://github.com/fac25/week2-db-Sumithra-Joe-Paz-Abdullah/blob/b543a36f38b1aab576324becce35afdb52dc3ca9/src/routes/location-route.js#L13

A status code 404 is usually served when a user tries to access a broken/old/non-existent route.

**Comment by Joe-Lindie** [comment]
Thanks. We managed to fix this issue
